name: Build

on:
  push:
    tags:
      - "*.*.*"

permissions:
  actions: read
  contents: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate tag format
        run: |
          echo "Using tag: ${{ github.ref_name }}"
          if ! [[ "${{ github.ref_name }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Tag format is invalid. Expected semantic versioning (e.g., 1.2.3)."
            exit 1
          fi
  macos:
    runs-on: macos-latest
    needs:
      - validate
    strategy:
      matrix:
        arch:
          - arm64
    steps:
      - uses: actions/checkout@v4
        with:
          repository: apple/swift-protobuf
          ref: ${{ github.ref_name }}
      - run: |
          swift build -c release
          mv .build/release/protoc-gen-swift protoc-gen-swift-macos-${{ matrix.arch }}
      - uses: actions/upload-artifact@v4
        with:
          name: protoc-gen-swift-macos-${{ matrix.arch }}
          path: protoc-gen-swift-macos-${{ matrix.arch }}
  linux:
    runs-on: ubuntu-latest
    needs:
      - validate
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v4
        with:
          repository: apple/swift-protobuf
          ref: ${{ github.ref_name }}
      - run: |
          swift build -c release --static-swift-stdlib
          mv .build/release/protoc-gen-swift protoc-gen-swift-linux-${{ matrix.arch }}
      - uses: actions/upload-artifact@v4
        with:
          name: protoc-gen-swift-linux-${{ matrix.arch }}
          path: protoc-gen-swift-linux-${{ matrix.arch }}
  release:
    runs-on: ubuntu-latest
    needs:
      - macos
      - linux
    steps:
      - uses: actions/download-artifact@v4
      - run: ls -l; ls -l protoc-gen-swift-*
      - uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          files: '**/protoc-gen-swift-*'
