name: Build

on:
  push:
    tags:
      - "*.*.*"

permissions:
  actions: read
  contents: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate tag format
        run: |
          echo "Using tag: ${{ github.ref_name }}"
          if ! [[ "${{ github.ref_name }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Tag format is invalid. Expected semantic versioning (e.g., 1.2.3)."
            exit 1
          fi
  build:
    runs-on: ${{ matrix.runs-on }}
    needs:
      - validate
    strategy:
      matrix:
        runs-on:
          - macos-15
          - ubuntu-24.04
          - ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          repository: apple/swift-protobuf
          ref: ${{ github.ref_name }}
      - id: build
        run: |
          if [[ ${{ matrix.runs-on }} == "macos-15" ]]; then
            executable="protoc-gen-swift-macos-arm64"
          elif [[ ${{ matrix.runs-on }} == "ubuntu-24.04" ]]; then
            executable="protoc-gen-swift-linux-amd64"
            flags="--static-swift-stdlib"
          elif [[ ${{ matrix.runs-on }} == "ubuntu-24.04-arm" ]]; then
            executable="protoc-gen-swift-linux-arm64"
            flags="--static-swift-stdlib"
          else
            echo "unsupported runner type: ${{ matrix.runs-on }}"
            exit 1
          fi
          swift build -c release $flags
          echo "executable=$executable" | tee -a $GITHUB_OUTPUT
          mv .build/release/protoc-gen-swift $executable
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.executable }}
          path: ${{ steps.build.outputs.executable }}
  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v4
      - run: ls -l
      - uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          files: '**/protoc-gen-swift-*'
